### ISSUE TITLE
BUG: Unable to mark SMS as read in the Status bar after quick reply

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Messages#10]
Hello, there is one issue with the Status bar reply: 

DESCRIPTION
It is unable to mark SMS as read in the Status bar after I make quick reply on this SMS. The "Mark as read" button does not work. So i have to swipe to right to make this SMS disappear.

STEPS
1. Replied on SMS from the Status bar (quick answer)
2. I want to close this SMS (remove it from the Status bar) and mark it as Read, but it is not possible - the button do not react

EXPECTED
The "Read" button should work.

OBSERVATIONS
The (quick) answered SMS is persisted in the Status bar, because it the "Mark as read" button does not work (no reaction).

Thank you for fixing this.

p.s.: Lineage0S 16.0

**Comment by Goodwy** [comment]
Fixed
