### ISSUE TITLE
BUG: Unable to copy phone number from the SMS

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Messages#15]
Hello, there is a bug in Right Messages. When somebody send me phone number inside of the SMS in format "+39 111 222 333", and I try to copy this number via single tick function, I got copied only "+39", instead of "+39 111 222 333". Maybe Right Message app do not count with phone number format with spaces and takes only first number ( "+39"). Anyway, this is quite common format of phone numbers (with spaces). 
So please, fix it. 
Thank you.

**Comment by Goodwy** [comment]
The error is not confirmed, copying is correct on the current version.
