### ISSUE TITLE
BUG: Unable to delete just one message from me as a sender

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Messages#17]
Hello, there is one bug. When I try to delete just one message (from me as a sender's side) in my SMS thread, it is not possible. I can choose the concrete SMS to delete, BUT when I tap on the Delete icon, all SMS are selected (or at least many of them). The only way is to deselect the rest.. With SMSes from other side (who send me SMS), it works. 

With native Google SMS app, the deletion works, but when I go back to Right Messages app, the deleted SMSes they are visible for a second again, then disappear.. Very strange behaviour. 

Can you fix it, please? 

p.s.: LineageOS 16.0

**Comment by Goodwy** [comment]
It is not confirmed on the current version.
