### ISSUE TITLE
BUG: Unable to download multiple pictures from MMS 

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Messages#19]
Hello, I found an issue in Right Messages. When I receive just one picture there is no problem to download it via long press on the picture and save it via "Save as" icon. But when I receive more pictures and I long press on any of these, the picture segment is marked, but I miss there an option to save it. I simply can not as there is no "Save as" icon anymore. 

Can you fix it, please? 

Thank you.

**Comment by Goodwy** [comment]
Fixed
