### ISSUE TITLE
IMPROVEMENT: Unable to to choose a SIM in "fast reply" (main bar) with the phone with two SIMs (two-SIM phone) 

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Messages#21]
Hello, I found one back-log with "fast reply" froim main bar. I have a phone with two SIMs. It is impossible to choose which SIM to use for the reply, i.e. there is s possibility to answer on the SMS only with SIM 1, there is no choice for SIM 2. 

Can you add there the little button for choosing which SIM to use, please? 

Thank you.

**Comment by Goodwy** [comment]
Fixed on version 5.1.1.
Now the reply will be sent from the SIM card to which the message was sent.
