### ISSUE TITLE
IMPROVEMENT: Confirmation which SMS to choose after the Send button (two-SIM phone) 

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Messages#23]
Hello, can you add the feature for two-SIM phone for sending an SMS, similar as it works on "Right Dialer"? When I call the number, the pop-up window will appear to ask me if I want to call via SM 1 or SIM 2. Can you implement similar feature to "Messages", please? After clicking the Send button, the SMS will not be send, but popup window will appear for choosing which SIM to use. 

Thank you!

**Comment by Goodwy** [comment]
Implemented in the next version 5.1.1

**Comment by Moostek** [comment]
Hello, thank you for adding this feature to the version 5.1.1. But I would like report a little bug. I have two-SIM phone, but in the menu it is doubled, so it is: "SIM1", "SIM2", "SIM1", "SIM2" - so there 4 items, there should be just two. Can you fix it? 

Also, I would like to ask if is it possible to have different menu, more like button style. It means that the switch window will contains two circle buttons side by side as "SIM1", "SIM2". Will it be possible, please? 

Thank you!

**Comment by Goodwy** [comment]
Fixed on version 5.1.1
