### ISSUE TITLE
IMPROVEMENT: addition of the date and time to every sent and received SMS 

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Messages#24]
Hello, I found one thing is missing in Right Messages: the date and time of every received and sent SMS: 
a) I can see dates and time with only some of my sent SMS, but not all, 
b) I can not see date and time of any received SMS. 
And this is problematic, because sometimes I need to know when I have received (or sent) some some SMS and I can not find it out. 

Can you add the date and time to every SMS in the thread? 

Also, it will be nice if the date and time of received SMS will be moved to the left side, and the date and time of sent SMS will be moved to the right side - just right above of every single SMS. 

Thank you.

**Comment by Goodwy** [comment]
Hello, the date and time are displayed above the post.

**Comment by Moostek** [comment]
Well. I can not see the date and time related with every SMS. Some SMS do not have the date and time.

**Comment by Goodwy** [comment]
If the date and time of several messages are the same, it is not repeated each time, but is written at the top common for all these messages.

**Comment by Moostek** [comment]
Well, it is misleading. In some of my communications I miss the dates and time both of received and sent SMS (also in the combination of received and sent SMS as well). Btw, none of my SMS I send in the same time. As I watch some threads now, I really can not say what is the date and time the concrete SMS was sent/received. 

Can you add an option to have a date and time for every single SMS, please? 
Thank you.

**Comment by Goodwy** [comment]
Messages are grouped by date and time, you can open a property if you want to, there is a date there too.
