### ISSUE TITLE
Harmonize the size of icons and titles across all Right apps (focused on "Right Messages") 

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Messages#4]
Hello, do you think you can harmonize the size of icons and titles in between the "Right Contacts & Right Dialer" and the "Right Messages" app? I prefer the smaller ratio of "Right Contacts & Dialer" - the icons and titles are smaller, so the display contains more informations. It will be great to have this smaller size in "Right Messages" home page. It will be cool to have new setting for this;) Thank you.

**Comment by Goodwy** [comment]
Added customisation of the size of chat icons.
