### ISSUE TITLE
Change the colour of the cursor and the buttom bubble (for dark skins) 

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Messages#6]
Hello, i sat up "Right Messages" as a default SMS client. I use the dark skin in my Lineage 16.0. The problem is that when i write SMS and i mark on text somewhere else, the cursor and the bottom bubble is also black, so it very hard to find where i am. Can you make the cursor and the bottom bubble green, please? Or can you make some setting to set up the colour of of the cursor with a buttom bubble? 
It will be much much better to proceed in textations;)

**Comment by Goodwy** [comment]
Version 4 added the ability to change the colors of the cursor.
