### ISSUE TITLE
Wrong translations at Status Bar reply 

### ISSUE THREAD

**Issue by Moostek** [Goodwy/Messages#9]
Hello, in the Status bar reply there is wrong translation. I use Czech localization, and there is still "Me", but there should be "Já" (Czech translation of English "Me"). 

Thank you for the fix.

**Comment by Goodwy** [comment]
Hello, can you attach a screenshot of this inscription?

**Comment by Moostek** [comment]
Hello, well, it seems that I checked this temporarily with another SMS app. Right Messages do not contain any contact addressing. 

Anyway, in settings menu there is lot of untranslated expressions.
